<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="Helper.Test_custTestNG" tests="3" time="0.005" ignored="0" failures="1" timestamp="11 Jan 2017 06:28:03 GMT" skipped="0" hostname="XEN-783" errors="0">
  <testcase name="testThree" time="0.000" classname="Helper.Test_custTestNG"/>
  <testcase name="testTwo" time="0.001" classname="Helper.Test_custTestNG">
    <failure type="java.lang.AssertionError" message="expected [AutomationgTest] but found [AutomationgTesting]">
      <![CDATA[java.lang.AssertionError: expected [AutomationgTest] but found [AutomationgTesting]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Helper.Test_custTestNG.testTwo(Test_custTestNG.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at Helper.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:46)
	at Helper.TestNgXmlUsingCode.main(TestNgXmlUsingCode.java:51)
]]>
    </failure>
  </testcase> <!-- testTwo -->
  <testcase name="testOne" time="0.004" classname="Helper.Test_custTestNG"/>
</testsuite> <!-- Helper.Test_custTestNG -->
