<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="ProgramSuite" duration-ms="20" started-at="2017-01-11T06:28:03Z" finished-at="2017-01-11T06:28:03Z">
    <groups>
    </groups>
    <test name="ProgramTest" duration-ms="20" started-at="2017-01-11T06:28:03Z" finished-at="2017-01-11T06:28:03Z">
      <class name="Helper.Test_custTestNG">
        <test-method status="PASS" signature="testOne()[pri:0, instance:Helper.Test_custTestNG@2eafffde]" name="testOne" duration-ms="4" started-at="2017-01-11T11:58:03Z" finished-at="2017-01-11T11:58:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="PASS" signature="testThree()[pri:0, instance:Helper.Test_custTestNG@2eafffde]" name="testThree" duration-ms="0" started-at="2017-01-11T11:58:03Z" finished-at="2017-01-11T11:58:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="FAIL" signature="testTwo()[pri:0, instance:Helper.Test_custTestNG@2eafffde]" name="testTwo" duration-ms="1" started-at="2017-01-11T11:58:03Z" finished-at="2017-01-11T11:58:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [AutomationgTest] but found [AutomationgTesting]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [AutomationgTest] but found [AutomationgTesting]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Helper.Test_custTestNG.testTwo(Test_custTestNG.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at Helper.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:46)
	at Helper.TestNgXmlUsingCode.main(TestNgXmlUsingCode.java:51)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
      </class> <!-- Helper.Test_custTestNG -->
    </test> <!-- ProgramTest -->
  </suite> <!-- ProgramSuite -->
</testng-results>
